/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bbm_client;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maxime
 */
public class IHMOperateur extends VuePrincipale {
    private Object tablePanierProduit1;

    /**
     * Creates new form IHMOperateur
     * @param c
     */
    public IHMOperateur(Controleur c) {
        initComponents();
        this.add(jPanel1);
        this.setSize(1000,800);
        this.setVisible(true);
        controleur = c;
        
        
        //TESTS FONCTIONNEL A GARDER
        //vueOp = new IHMOperateur(this);
        affichesLignes();
    }

    /**
     *Permet d'afficher une founée passée en paramètre sur la vue Opérateur
     * @param donnee
     */
    @Override
    public void afficheLigneFournee(ArrayList donnee){
        DefaultTableModel table = (DefaultTableModel) tableDesCuissons1.getModel();
        String datas[] = {"0","0","0","0","0"}; //Initialisation ligne
        //Récupération et traitement des données
        datas[0]=(String) donnee.get(0); //Produit
        datas[1]=(String) donnee.get(1); //Quantité
        datas[2]=(String) donnee.get(2); //Debut
        datas[3]=(String) donnee.get(3); //Fin
        datas[4]=(String) donnee.get(4); //Temps
        table.addRow(datas);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelBBMOPERATEUR1 = new javax.swing.JLabel();
        Deconnexion1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDesCuissons1 = new javax.swing.JTable();
        labelTableauDesCuissons1 = new javax.swing.JLabel();

        labelBBMOPERATEUR1.setText("BBM  - OPERATEUR");

        Deconnexion1.setText("Déconnexion");
        Deconnexion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deconnexion1ActionPerformed(evt);
            }
        });

        tableDesCuissons1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Produit", "Quantité", "Debut", "Fin", "Temps"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableDesCuissons1);

        labelTableauDesCuissons1.setText("Tableau des cuissons");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(labelBBMOPERATEUR1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Deconnexion1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(labelTableauDesCuissons1)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE))))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelBBMOPERATEUR1)
                        .addComponent(Deconnexion1))
                    .addGap(26, 26, 26)
                    .addComponent(labelTableauDesCuissons1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(32, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Deconnexion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deconnexion1ActionPerformed
        super.deconnexion();
    }//GEN-LAST:event_Deconnexion1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deconnexion1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelBBMOPERATEUR1;
    private javax.swing.JLabel labelTableauDesCuissons1;
    private javax.swing.JTable tableDesCuissons1;
    // End of variables declaration//GEN-END:variables

    private void affichesLignes() {
        recupFournees() ;
    }

    private void recupFournees() {
        
    }
}
